version: '3'

services:
  mysql:
    container_name: mysql
    build: ./mysql
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - nginx-node
    # ports:
    #   - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3

  node-app:
    container_name: node-app
    build: ./node
    volumes:
      - ./node:/home/node/api
    networks:
      - nginx-node
    # ports:
    #   - 3333:3333
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - node-app
    networks:
      - nginx-node

networks:
  nginx-node:
    driver: bridge
